import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CountryItem from "../components/CountryItem/CountryItem";
import { Country } from "../interfaces";

type HomeProps = {
  countries: Country[];
  isSuccess: boolean;
};

const Home = ({ countries, isSuccess }: HomeProps) => {
  console.log("home", countries);
  console.log("isSuccess", isSuccess);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isSuccess ? (
          countries?.map((country, index: number): any => (
            <CountryItem country={country} />
          ))
        ) : (
          <div>error</div>
        )}
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  try {
    console.log("response->test");

    const response = await fetch(
      "https://restcountries.com/v3.1/all?fields=flags,capital,name,population"
    );
    const countries: Country[] = await response.json();
    // console.log("response", countries);

    return {
      props: {
        countries,
        isSuccess: true,
      },
    };
  } catch (error) {
    return {
      props: {
        countries: [],
        isSuccess: false,
      },
    };
  }
};
export default Home;
